# Generated by Django 2.2.1 on 2019-07-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20190723_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=30)),
                ('title', models.TextField()),
                ('movie_path', models.TextField()),
                ('cover_name', models.TextField()),
                ('cover_path', models.TextField()),
                ('acter', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('publisher', models.CharField(max_length=30)),
                ('creater', models.CharField(max_length=30)),
                ('serial', models.TextField()),
            ],
        ),
    ]
