# Generated by Django 2.2.1 on 2019-07-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='creater',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='serial',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='acter',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='publisher',
            new_name='studio',
        ),
    ]
